### ISSUE TITLE
Assign vlan to VM 

### ISSUE THREAD

**Issue by selund** [ananace/foreman_hyperv#15]
Would it be hard to be able to set witch vlan a interface should be connected to?

**Comment by ace13** [comment]
There's an issue about this currently up on ace13/fog-hyperv#16, sadly it's not as simple as just providing a number.

It's most definitely planned for though.

**Comment by selund** [comment]
Hmm, how do you control which vlan a vm  is created with then? Not possible? 
Am I missing something?

**Comment by ace13** [comment]
Right now, setting the VLAN will need to be a manual action on the VM.

There are still some pieces left before I can do VLAN settings automatically through Foreman.

**Comment by ace13** [comment]
VLAN assignment should hopefully be in place as of 6b85dcb - though I won't have time to personally test it for a while, got a deadline for something else that's rapidly approaching.

Please try it out if you can, hopefully it's enough to get you going for now.

**Comment by ananace** [comment]
Going to close this as working, to clear up the issue list slightly, put up a new issue for interface-specific VLAN settings
