### ISSUE TITLE
Support for hyper-v legacy Network Adapter

### ISSUE THREAD

**Issue by youth315** [ananace/foreman_hyperv#18]
Is it support hyper-v legacy network adapter? I don't see the legacy network adapter when creating the Hyper-V vm through foreman.

**Comment by ananace** [comment]
Currently there's no support for creating legacy network adapters, though it shouldn't be that hard to implement - if that's something that's required for your use case?

**Comment by youth315** [comment]
Yes, i want to batch deploy the Hyper-V templates through pxe boot. but seems it can't create the legacy network adapter which will show boot failed.

**Comment by ananace** [comment]
I hacked together some support for legacy network adapters in 082d95e0cf0942e84846b2de99fffc9d3f055606, will require ananace/fog-hyperv@d4bf0fcdef691573c25744c3f3930961d5f767d6 as well though.

Hopefully that's enough for you to be able to use it?

**Comment by youth315** [comment]
Thanks for your great support. The new scripts are working fine in my environment. Thanks very much.

**Comment by ananace** [comment]
Good to hear that the hack works for you :smiley:
