### ISSUE TITLE
Is this module maintained?

### ISSUE THREAD

**Issue by tek0011** [ananace/foreman_hyperv#21]
No update in a year.  Is this module working as intended and still maintained?

**Comment by ananace** [comment]
We are currently migrating away from Hyper-V at work, so I haven't really
had much of a paid reason to continue development.

The core features are fully functional though, you can manage simple VMs
without issue, and even some more advanced features have been implemented.

I'll still happily respond to issues and PRs, though I wouldn't be adverse
to handing over maintainership to someone with more available time to spend
on it.

**Comment by tek0011** [comment]
Thanks for the reply!  We also dont use Hyper-V much.   We used to be a Hyper-V shop until we implemented Foreman and found out it didnt really support it.  We've since moved everything to ESX.   If it does the basics of getting a machine spun up and provisioned, Ill check it out.
